services:
  - type: web
    name: portfolio-django
    env: python
    buildCommand: "./build.sh"
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_SETTINGS_MODULE
        value: "portfolio.settings"

databases:
  - name: portfolio-db
    plan: free