# Generated by Django 5.2.7 on 2025-10-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='detail_html_file',
            field=models.FileField(blank=True, help_text='Upload HTML file for project details', null=True, upload_to='content_html/'),
        ),
    ]
