# Generated by Django 5.2.7 on 2025-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contentitem_detail_html_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Content Item', 'verbose_name_plural': 'Content Items'},
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('project', 'Project'), ('skill', 'Skill'), ('education', 'Education'), ('experience', 'Experience'), ('certification', 'Certification'), ('internship', 'Internship'), ('hackathon', 'Hackathon'), ('gallery', 'Gallery Item'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Link to live demo or project', verbose_name='Demo URL'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='description',
            field=models.TextField(help_text='Full description of the content item'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='detail_html_file',
            field=models.FileField(blank=True, help_text='Custom HTML file for detailed project pages', null=True, upload_to='content_html/'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='end_date',
            field=models.DateField(blank=True, help_text='When this project/work ended (leave blank if ongoing)', null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to GitHub repository', verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image for this content', null=True, upload_to='content_images/'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Display this item on the website'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this item in the featured section'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Certificate, document, or detailed PDF', null=True, upload_to='content_pdfs/'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for cards and previews', max_length=300),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='start_date',
            field=models.DateField(blank=True, help_text='When this project/work started', null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma-separated list of technologies used', max_length=500),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='video',
            field=models.FileField(blank=True, help_text='Demo or presentation video', null=True, upload_to='content_videos/'),
        ),
    ]
